### PR TITLE
styling with styler

### PR DESCRIPTION
**Pull request by lorenzwalthert**
conservative styling with scope = "spaces" and strict = FALSE.

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
Reference: https://github.com/krlmlr/tidyr/pull/1
cc: @krlmlr

**Comment by hadley** [comment]
Thanks!

**Comment by lorenzwalthert** [comment]
Should we do a follow-up with `scope > "spaces"`?

**Comment by hadley** [comment]
Yeah, let's take a look. Does styler have the ability to ignore `tribble()` spacing yet?

**Comment by lorenzwalthert** [comment]
Ok, cool. No, it has not. Maybe we should add that. We can use `strict = FALSE`, which just ensures *at least* one space around certain operators. That should leave many tribble calls  untouched.

**Comment by lorenzwalthert** [comment]
I opened #317 to discuss that further (and labeled it with `Status: Postponed` and closed it for now because me and @krlmlr don't really have time to work on it now).

**Pull request merged**
