### PR TITLE
Rename data to .data in ... using functions

### LINKED ISSUE #759: Use .data in pack()
In `dplyr` functions, the first argument are mostly `.data` to prevent possible conflicts. But in ` tidyr`, most functions use `data` as the first argument. And it creates an issue that when setting `data` as column name.

For example:

Since `data` is already used as the first argument of `pack()` function, when using "data" as a column, it will throw an error message. 

```r
df <- tibble(x1 = 1:3, x2 = 4:6, x3 = 7:9, y = 1:3)
df %>% pack(data = c(x1, x2, x3), y = y) 
```
throws an error message:
```r
Error: All elements of `...` must be named
```

The same applies to at least `pack`, `unpack`, `chop` and `unchop`

### PR DESCRIPTION
**Pull request by hadley**
Fixes #759

### CODE REVIEW

**Comment by hadley** [comment]
@lionel- can you see any way to do this that won't break existing method definitions?

**Comment by lionel-** [comment]
I think adding `data` back for a period of deprecation should work. If they were generic it would probably be harder. Those signatures will look messy if only one of the arguments is prefixed with a dot. Perhaps it's not too late to change the other arguments as well, since they are relatively new?

One alternative is to keep the signatures as is and require using `:=` to pass arbitrary names through `...` without matching on formal parameters. That's not consistent with our style guide though.

**Comment by hadley** [comment]
I think I'll split the difference and just fix `pack()` since `unnest()` is a generic.

**Comment by hadley** [comment]
Oh and `...` is deprecated in `unnest()` so it doesn't need it.

**Pull request closed without merging**
