### PR TITLE
Allow pivot_longer's values_transform argument to take a single function

### LINKED ISSUE #1035: values_transform should accept a single function
I would expect that providing a single function to `values_transform` in `pivot_longer()` would apply to each column selected for pivoting (x and y in my example). This would be consistent to the recent change in `pivot_wider()`, from the News: 

> arguments values_fn and values_fill can now be single values; you now only need
to use a named list if you want to use different values for different value columns (#739, #746). 
They also get improved errors if they're not of the expected type.

```r
library(tidyr)
packageVersion("tidyr")
#> [1] '1.1.0'

df <- data.frame(x = 1:5, y = letters[1:5], stringsAsFactors = FALSE)

pivot_longer(df, c(x, y), values_transform = as.character)
#> Error: Can't combine `x` <integer> and `y` <character>.
```
If I do `pivot_longer(df, c(x, y), values_transform = list(value = as.character))`, it works as expected. 

If you agree this is a desired change, I would be happy to submit a PR, and I will also create a similar issue for `values_ptypes` (where I always face the same confusion).

### PR DESCRIPTION
**Pull request by smingerson**
Closes #1035.

### CODE REVIEW

**Review by hadley — COMMENTED** [review]
Looks good! Do the docs need an update too?

**Comment by smingerson** [comment]
Yes, they do. Here I was, so impressed with myself for remembering a news item! The `values_transform` description is shared with `names_transform`. Should I add similar functionality to `names_transform` and update the docs, or split the documentation? I think it makes sense for both to allow functions, just seems a lot less useful for names.

**Comment by hadley** [comment]
Yeah, I think it would be easier to be consistent.

**Comment by smingerson** [comment]
Should be ready for another look when you have time.

**Comment by hadley** [comment]
@DavisVaughan can you finish off the review please?

**Comment by DavisVaughan** [comment]
Closed in favor of broader changes added in https://github.com/tidyverse/tidyr/pull/1287, I mentioned @smingerson in the NEWS bullet

**Pull request closed without merging**
