### PR TITLE
Fix tests with dev vctrs

### PR DESCRIPTION
**Pull request by krlmlr**
Broken since https://github.com/r-lib/vctrs/issues/660. Also added fixes so that tidyr now tests correctly with dev tibble.

CC @DavisVaughan (I can't request a review).

### CODE REVIEW

**Comment by DavisVaughan** [comment]
I suppose it is worth discussing if continuing to return a `list_of` is useful?

I think `nest()` will have the same issue?

**Comment by krlmlr** [comment]
`nest()` is fixed with a `vec_split_list_of()` implementation, which perhaps might live in vctrs?

**Comment by krlmlr** [comment]
Are you suggesting to not return `list_of`? I rather like explicitly typed columns.

**Comment by DavisVaughan** [comment]
It's probably worth using `new_list_of()` for performance since you know the input structure

``` r
df <- data.frame(x = 1, y = 2)
x <- rep_len(list(df), 1000)

library(vctrs)

bench::mark(
  as_list_of(x, .ptype = df),
  new_list_of(x, ptype = vec_ptype(df))
)
#> # A tibble: 2 x 6
#>   expression                                min  median `itr/sec` mem_alloc
#>   <bch:expr>                            <bch:t> <bch:t>     <dbl> <bch:byt>
#> 1 as_list_of(x, .ptype = df)             1.87ms  2.41ms      403.    80.8KB
#> 2 new_list_of(x, ptype = vec_ptype(df)) 18.95µs 23.14µs    42927.    17.9KB
#> # … with 1 more variable: `gc/sec` <dbl>
```

<sup>Created on 2020-01-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by hadley** [comment]
Sorry I missed this; now in v1.0.1 branch, which I'm about to release to CRAN.

**Pull request closed without merging**
