### PR TITLE
_if variants for gather and nest

### PR DESCRIPTION
**Pull request by atusy**
I added _if variants for gather and nest owing to my feature request (https://github.com/tidyverse/tidyr/issues/477).

### CODE REVIEW

**Comment by atusy** [comment]
At first opening, travis-ci failed due to time out.
I checked travis goes well in a forked repository, and then tried to run travis again by close and re-open PR.
Then codecov happens to fail.

**Comment by atusy** [comment]
I found I have to write tests

**Comment by lionel-** [comment]
You can commit --amend and then push --force to trigger a Travis rebuild, if you close/open the PR you're sending many notifications to people subscribed to the repo ;)

**Comment by atusy** [comment]
Thank you. I do that way from next time.

**Comment by hadley** [comment]
I think we're going to tackle this in a slightly more general way, probably via new tooling in tidyselect. Thanks for brining the problem to our attention.

**Pull request closed without merging**
