### PR TITLE
Don't create unspecified vectors when unchopping empty non-lists

### PR DESCRIPTION
**Pull request by lionel-**

### CODE REVIEW

**Comment by DavisVaughan** [comment]
Reminder that this will be closed by #888 (I don't think I can link them to auto close at this point)

**Comment by jennybc** [comment]
> Reminder that this will be closed by #888 (I don't think I can link them to auto close at this point)

@DavisVaughan You can edit the PR description, i.e. add the text needed to the existing "Part of #xyz
Closes #abc". At least I sure think that works. The link-based auto-closing is determined at PR merge time, not PR creation time.

**Comment by DavisVaughan** [comment]
> link-based auto-closing is determined at PR merge time

Ah I thought it was creation time, thanks!

**Comment by hadley** [comment]
Since this is superseded by #888, I'm just going to close this one now.

**Pull request closed without merging**
