### PR TITLE
purrr removal #941

### PR DESCRIPTION
**Pull request by rjpat**
To address issue #941 

Think my replacement for [`purrr::transpose()`](https://github.com/rjpat/tidyr/blob/86bec61f3b9a7605d0361acbb6e0486093ea6f88/R/utils.R#L117) and [this line](https://github.com/rjpat/tidyr/blob/86bec61f3b9a7605d0361acbb6e0486093ea6f88/R/extract.R#L71) should be reviewed as not particularly happy with them but don't have the mental model of what would be better.

This has left the following with `{purrr}` functions;

1. `hoist()`
2. `unnest_*`
3. `separate_rows()` as it has `purrr::modify_at()` in it

### CODE REVIEW

**Comment by hadley** [comment]
I'm now wondering whether or not this is worth it — it's a lot more work than I had anticipated, and purrr is not a very heavy package.

**Comment by rjpat** [comment]
I agree it did touch a lot of functions and may not be worth going from tidyverse to base R for a small performance gain

**Comment by hadley** [comment]
Btw why do you think there will be a performance gain?

**Comment by rjpat** [comment]
Did a very quick microbenchmark of pivot_wider and there was a fractional speed increase. Probably not enough of a sample set for me to have mentioned it

**Comment by hadley** [comment]
Ah ok, cool, just wanted to make sure there wasn't an obvious performance issue in purrr.

**Pull request closed without merging**
