### PR TITLE
Fix/599

### LINKED ISSUE #599: `pivot_wider()` issue with pivoting to 1 row and having multiple values
When "widening" to 1 row, I think there is an issue if you have multiple value columns. I can't really tell you why you'd want to do this, but I think it is a valid transformation.

``` r
suppressPackageStartupMessages({
  library(tidyr)
  library(tibble)
  library(dplyr)
})
#> Warning: package 'tibble' was built under R version 3.5.2

warpy <- as_tibble(warpbreaks)

warpy_id <- warpy %>%
  group_by(wool, tension) %>%
  mutate(id = row_number()) %>%
  ungroup()

# widen to one row
warpy_id %>%
  pivot_wider(names_from = c(tension, wool, id), values_from = breaks)
#> # A tibble: 1 x 54
#>   L_A_1 L_A_2 L_A_3 L_A_4 L_A_5 L_A_6 L_A_7 L_A_8 L_A_9 M_A_1 M_A_2 M_A_3
#>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1    26    30    54    25    70    52    51    26    67    18    21    29
#> # … with 42 more variables: M_A_4 <dbl>, M_A_5 <dbl>, M_A_6 <dbl>,
#> #   M_A_7 <dbl>, M_A_8 <dbl>, M_A_9 <dbl>, H_A_1 <dbl>, H_A_2 <dbl>,
#> #   H_A_3 <dbl>, H_A_4 <dbl>, H_A_5 <dbl>, H_A_6 <dbl>, H_A_7 <dbl>,
#> #   H_A_8 <dbl>, H_A_9 <dbl>, L_B_1 <dbl>, L_B_2 <dbl>, L_B_3 <dbl>,
#> #   L_B_4 <dbl>, L_B_5 <dbl>, L_B_6 <dbl>, L_B_7 <dbl>, L_B_8 <dbl>,
#> #   L_B_9 <dbl>, M_B_1 <dbl>, M_B_2 <dbl>, M_B_3 <dbl>, M_B_4 <dbl>,
#> #   M_B_5 <dbl>, M_B_6 <dbl>, M_B_7 <dbl>, M_B_8 <dbl>, M_B_9 <dbl>,
#> #   H_B_1 <dbl>, H_B_2 <dbl>, H_B_3 <dbl>, H_B_4 <dbl>, H_B_5 <dbl>,
#> #   H_B_6 <dbl>, H_B_7 <dbl>, H_B_8 <dbl>, H_B_9 <dbl>

set.seed(123)
warpy_id2 <- warpy_id %>%
  mutate(breaks2 = rnorm(n()))

# widen to one row
warpy_id2 %>%
  pivot_wider(names_from = c(tension, wool, id), values_from = c(breaks, breaks2))
#> Warning: Values in `breaks` are not uniquely identified; output will contain list-cols.
#> * Use `values_fn = list(breaks = list)` to suppress this warning.
#> * Use `values_fn = list(breaks = length)` to identify where the duplicates arise
#> * Use `values_fn = list(breaks = summary_fun)` to summarise duplicates
#> Error: `x` and `by` must have same size
#> Backtrace:
#>      █
#>   1. └─`%>%`(...)
#>   2.   ├─base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
#>   3.   └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
#>   4.     └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
#>   5.       └─global::`_fseq`(`_lhs`)
#>   6.         └─magrittr::freduce(value, `_function_list`)
#>   7.           ├─base::withVisible(function_list[[k]](value))
#>   8.           └─function_list[[k]](value)
#>   9.             └─tidyr::pivot_wider(...)
#>  10.               └─tidyr:::vals_dedup(key = val_id, val = val, value = value, summarize = values_fn[[value]])
#>  11.                 └─vctrs::vec_split(val, key)

# you can do everything else...
warpy_id2 %>%
  pivot_wider(names_from = c(tension, wool), values_from = c(breaks, breaks2))
#> # A tibble: 9 x 13
#>      id breaks_L_A breaks_M_A breaks_H_A breaks_L_B breaks_M_B breaks_H_B
#>   <int>      <dbl>      <dbl>      <dbl>      <dbl>      <dbl>      <dbl>
#> 1     1         26         18         36         27         42         20
#> 2     2         30         21         21         14         26         21
#> 3     3         54         29         24         29         19         24
#> 4     4         25         17         18         19         16         17
#> 5     5         70         12         10         29         39         13
#> 6     6         52         18         43         31         28         15
#> 7     7         51         35         28         41         21         15
#> 8     8         26         30         15         20         39         16
#> 9     9         67         36         26         44         29         28
#> # … with 6 more variables: breaks2_L_A <dbl>, breaks2_M_A <dbl>,
#> #   breaks2_H_A <dbl>, breaks2_L_B <dbl>, breaks2_M_B <dbl>,
#> #   breaks2_H_B <dbl>

# I think I expect this ugly mess
bind_cols(
  pivot_wider(warpy_id2, id_cols = -breaks2, names_from = c(tension, wool, id), values_from = breaks, names_prefix = "breaks_"),
  pivot_wider(warpy_id2, id_cols = -breaks, names_from = c(tension, wool, id), values_from = breaks2, names_prefix = "breaks2_")
)
#> # A tibble: 1 x 108
#>   breaks_L_A_1 breaks_L_A_2 breaks_L_A_3 breaks_L_A_4 breaks_L_A_5
#>          <dbl>        <dbl>        <dbl>        <dbl>        <dbl>
#> 1           26           30           54           25           70
#> # … with 103 more variables: breaks_L_A_6 <dbl>, breaks_L_A_7 <dbl>,
#> #   breaks_L_A_8 <dbl>, breaks_L_A_9 <dbl>, breaks_M_A_1 <dbl>,
#> #   breaks_M_A_2 <dbl>, breaks_M_A_3 <dbl>, breaks_M_A_4 <dbl>,
#> #   breaks_M_A_5 <dbl>, breaks_M_A_6 <dbl>, breaks_M_A_7 <dbl>,
#> #   breaks_M_A_8 <dbl>, breaks_M_A_9 <dbl>, breaks_H_A_1 <dbl>,
#> #   breaks_H_A_2 <dbl>, breaks_H_A_3 <dbl>, breaks_H_A_4 <dbl>,
#> #   breaks_H_A_5 <dbl>, breaks_H_A_6 <dbl>, breaks_H_A_7 <dbl>,
#> #   breaks_H_A_8 <dbl>, breaks_H_A_9 <dbl>, breaks_L_B_1 <dbl>,
#> #   breaks_L_B_2 <dbl>, breaks_L_B_3 <dbl>, breaks_L_B_4 <dbl>,
#> #   breaks_L_B_5 <dbl>, breaks_L_B_6 <dbl>, breaks_L_B_7 <dbl>,
#> #   breaks_L_B_8 <dbl>, breaks_L_B_9 <dbl>, breaks_M_B_1 <dbl>,
#> #   breaks_M_B_2 <dbl>, breaks_M_B_3 <dbl>, breaks_M_B_4 <dbl>,
#> #   breaks_M_B_5 <dbl>, breaks_M_B_6 <dbl>, breaks_M_B_7 <dbl>,
#> #   breaks_M_B_8 <dbl>, breaks_M_B_9 <dbl>, breaks_H_B_1 <dbl>,
#> #   breaks_H_B_2 <dbl>, breaks_H_B_3 <dbl>, breaks_H_B_4 <dbl>,
#> #   breaks_H_B_5 <dbl>, breaks_H_B_6 <dbl>, breaks_H_B_7 <dbl>,
#> #   breaks_H_B_8 <dbl>, breaks_H_B_9 <dbl>, breaks2_L_A_1 <dbl>,
#> #   breaks2_L_A_2 <dbl>, breaks2_L_A_3 <dbl>, breaks2_L_A_4 <dbl>,
#> #   breaks2_L_A_5 <dbl>, breaks2_L_A_6 <dbl>, breaks2_L_A_7 <dbl>,
#> #   breaks2_L_A_8 <dbl>, breaks2_L_A_9 <dbl>, breaks2_M_A_1 <dbl>,
#> #   breaks2_M_A_2 <dbl>, breaks2_M_A_3 <dbl>, breaks2_M_A_4 <dbl>,
#> #   breaks2_M_A_5 <dbl>, breaks2_M_A_6 <dbl>, breaks2_M_A_7 <dbl>,
#> #   breaks2_M_A_8 <dbl>, breaks2_M_A_9 <dbl>, breaks2_H_A_1 <dbl>,
#> #   breaks2_H_A_2 <dbl>, breaks2_H_A_3 <dbl>, breaks2_H_A_4 <dbl>,
#> #   breaks2_H_A_5 <dbl>, breaks2_H_A_6 <dbl>, breaks2_H_A_7 <dbl>,
#> #   breaks2_H_A_8 <dbl>, breaks2_H_A_9 <dbl>, breaks2_L_B_1 <dbl>,
#> #   breaks2_L_B_2 <dbl>, breaks2_L_B_3 <dbl>, breaks2_L_B_4 <dbl>,
#> #   breaks2_L_B_5 <dbl>, breaks2_L_B_6 <dbl>, breaks2_L_B_7 <dbl>,
#> #   breaks2_L_B_8 <dbl>, breaks2_L_B_9 <dbl>, breaks2_M_B_1 <dbl>,
#> #   breaks2_M_B_2 <dbl>, breaks2_M_B_3 <dbl>, breaks2_M_B_4 <dbl>,
#> #   breaks2_M_B_5 <dbl>, breaks2_M_B_6 <dbl>, breaks2_M_B_7 <dbl>,
#> #   breaks2_M_B_8 <dbl>, breaks2_M_B_9 <dbl>, breaks2_H_B_1 <dbl>,
#> #   breaks2_H_B_2 <dbl>, breaks2_H_B_3 <dbl>, breaks2_H_B_4 <dbl>,
#> #   breaks2_H_B_5 <dbl>, breaks2_H_B_6 <dbl>, …
```

<sup>Created on 2019-03-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

### PR DESCRIPTION
**Pull request by DavisVaughan**
Closes #599

### CODE REVIEW

**Comment by hadley** [comment]
In the future, can you please give your PRs more descriptive names — if any amount of time has elapsed (i.e. >1 min 😆) I will have no idea what issue you are referencing.

**Comment by jennybc** [comment]
> In the future, can you please give your PRs more descriptive names

Sidebar process observation: I now copy the issue's title (which will include its number), paste, and move the number to the front. It's annoyingly manual, but it helps me build all the right mental- and hyper-links.

**Comment by hadley** [comment]
I don't think the number is useful, since it should be included in one of the commit messages.

**Comment by jennybc** [comment]
I just like it for the prominent auto-hyperlink (which, yes, also shows up in some individual commit message).

**Comment by DavisVaughan** [comment]
In this particular case I just forgot to update the auto-generated PR title that came from the branch name. I'd argue those are almost never good PR names, and I kind of wish it always made me give a name manually.

**Pull request merged**
